# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: NodeJS CI with PostgreSQL
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: codex123
          POSTGRES_DB: my_waiter
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: create postgresql tables
      run: PGPASSWORD=codex123 psql -h localhost -U postgres -d my_waiter -a -f ./waiters-database.sql
    - name: run tests with postgresql
      run:
        npm test
      env:
        DATABASE_URL: postgres://postgres:codex123@localhost:5432/my_waiter
